import Head from 'next/head'
import styles from './home.module.scss'
import IndexLayout from '../layouts/IndexLayout';
import SearchByClass from '../components/search-class/searchByClass';
import SearchByStar from '../components/search-star/searchByStars';
import SearchByState from '../components/search-state/searchByState';

export default function Home() {

	return (
		<div className={styles.homePage}>
			<Head>
				<title>Future 5 Star</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.infoContainer}>
				<h1>Future Five Star National Recruit Database</h1>
				<p>Upgrade your <strong>Digital Footprint</strong> to enhance your brand. 
					Sync Data, and add more content to the database. Such as Highlight tapes, 
					Merch store, model/influencer Page, Logos , and more.</p>
			</div>
			<div className={styles.searchByContainer}>
				<div className={styles.stateContainer}>
					<h3>Search By State</h3>
					<SearchByState />
				</div>
				<div className={styles.classContainer}>
					<h3>Search By Class</h3>
					<SearchByClass />
				</div>
				<div className={styles.starsContainer}>
					<h3>Search By Star Rating</h3>
					<SearchByStar />
				</div>
			</div>
		</div>
	)
}

Home.PageLayout = IndexLayout;

